name: stencil-base
arguments:
  ciOptions:
    skipDocker: true
    skipE2e: true
  description: Base templates for a stencil backed service
  reportingTeam: fnd-dt
  releaseOptions:
    enablePrereleases: true
    prereleasesBranch: rc
modules:
  - name: github.com/getoutreach/stencil-template-base
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
replacements:
  github.com/getoutreach/stencil-base: ./
