name: stencil-base
arguments:
  description: Base templates for a stencil backed service
  reportingTeam: fnd-dt
  ciOptions:
    skipDocker: true
    skipE2e: true
  releaseOptions:
    enablePrereleases: true
    prereleasesBranch: rc
modules:
  - name: github.com/getoutreach/stencil-template-base
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/devbase
    channel: rc
replacements:
  github.com/getoutreach/stencil-base: ./
