name: stencil-base
arguments:
  ciOptions:
    skipDocker: true
    skipE2e: true
  confluenceSpaceKey: DT
  description: Base templates for a stencil backed service
  lifecycle: public_ga
  lintroller: platinum
  notifications:
    slackChannel: "#dt-notifications"
  releaseOptions:
    autoPrereleases: true
    enablePrereleases: true
    prereleasesBranch: main
  reportingTeam: fnd-dt
  tier: 2
modules:
  - name: github.com/getoutreach/stencil-template-base
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/stencil-outreach
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
  - name: github.com/getoutreach/stencil-base
    channel: rc
  - name: github.com/getoutreach/stencil-discovery
    channel: rc
  - name: github.com/getoutreach/stencil-pipeline
    channel: rc
replacements:
  github.com/getoutreach/stencil-base: ./
